#!/bin/bash

echo "Removing old version of Tusk..."

if command -v tusk &> /dev/null
then
  tusk stop
  tusk uninstall
  rm /usr/bin/tusk
  rm /usr/bin/tusk-server
fi

rm -rf /srv/*

echo "Installing new version..."

cp /home/mclytar/deploy/tusk/target/debug/tusk /usr/bin/
cp /home/mclytar/deploy/tusk/target/debug/tusk-server /usr/bin/

cp -r /home/mclytar/deploy/tusk/_srv/* /srv/

tusk install
tusk start

echo "Done!"