#!/bin/bash
TARGET="/home/mclytar/deploy/tusk/"
GIT_DIR="/home/mclytar/tusk.git"
BRANCH="main"

while read oldrev newrev ref
do
    if [ "$ref" = "refs/heads/$BRANCH" ];
    then
        # Unpack git repository.
        echo "Running as ${USER}"
        echo "Ref $ref received. Deploying ${BRANCH} branch to production..."
        git --work-tree=$TARGET --git-dir=$GIT_DIR checkout -f
        # Build the executables.
        cd $TARGET
        ~/.cargo/bin/cargo build
        # If compilation is successful, run the installation script.
        status=$?
        if [ $status -eq 0 ];
        then
            sudo /home/mclytar/install/tusk/install
        else
            echo "Unsuccessful compilation; installation aborted."
        fi
    else
        echo "Ref $ref received. Doing nothing: only the ${BRANCH} branch may be deployed."
    fi
done