[package]
name = "tusk-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.6"
actix-web = "4"
log = { version = "0.4", features = ["std", "serde"] }
simple_logger = "4"
tera = "1"
tusk-derive = { path = "../tusk-derive" }