[diesel]
url = "postgres://tusk-test:tusk-test@localhost/tusk-test"

[mail]
auth_user = "smtp_admin"
auth_password = "smtp_password"
email = "noreply@localhost"
hostname = "localhost"
port = 2525

[redis]
url = "redis://127.0.0.1:6379"

[ssl]
cert_file = "test-cert.pem"
key_file = "test-key.pem"

[tusk]
log_level = "info"
www_domain = "localhost"
api_domain = "localhost"

[tusk.contacts]
noreply = "noreply@localhost"
support = "support@localhost"

[tusk.serve]
root = "test_srv/"
tera_templates = "test_srv/tera/"
static_files = "test_srv/static/"
user_directories = "test_srv/storage/"

[tusk.ui]
icon_filetype = "svg"